import type { Metadata } from "next";

import "./globals.css";
import { Nunito_Sans } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunito_sans.className}>
      <body>{children}</body>
    </html>
  );
}
